#
#
#
#


testing: True

test_images:
- "imgs/2024-06-18/snapshot_16529us_01_02.bmp"
- "imgs/2024-06-18/snapshot_16529us_01_08.bmp"


tag:
    size: 0.131                                     # Physical size of the AprilTag [m]


camera:
    file: "../python/config/camera_nominal.yaml"    # path to camera calibration file


expected_markers: 2                                 # number of expected markers (valid blobs)